### ISSUE TITLE
This project needs a champion and support

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin4net#230]
We moved this repo into the main zipkin repo after some deliberation and a perception that multiple folks would be maintaining it. Currently, it isn't getting enough love and has an increasing backlog as well unmerged large pull requests. We routinely get support questions with few replies from folks who know this library.

We need to decide what to do about this @openzipkin/core

**Comment by jcarres-mdsol** [comment]
Last PR was merged 2 weeks ago, does not seem so bad to me. 
@fedj  can you give us some background?

**Comment by adriancole** [comment]
there are numerous large pull requests not merged and we constantly get
questions on gitter. merging small pull requests is good but that is
different than owership

**Comment by basvanbeek** [comment]
Let's put in an effort to find a champion as it would be sad to see this be moved out of the openzipkin organization. It could be a good project for someone looking for a way into .net oss and I think that most of us in core would be willing to chip in and mentor on required domain knowledge.

In case we don't find anyone we should move to contrib to provide the correct signal that this is indeed a project that turned into lacking official support.

By making it clear and apparent we intend to move to contrib if we don't find new stewardship it might be that actual and prospective users of this library start to contribute. Sometimes people / companies just need a little incentive.

**Comment by fedj** [comment]
@jcarres-mdsol To be totally transparent, this project is more in a support mode (aka check incoming PRs and merge them) more than real support (moving to v2, adressing issues on gitter, ...) since I moved from my original company and I don't have much time to work on it.
The migration to v2 has been a bit painful as it degraded the performances drastically which was a no-go for us back in time.
Finding a champion would be indeed a really good thing because this lib is battlefield tested and it would be sad to fall again in the same pitfalls.

**Comment by codefromthecrypt** [comment]
last workshop, MdSol mentioned they are using this in production and are happy to support the project. The main thing was closing some huge PRs as they didn't have resources to rebase them. As they just pushed a release, I think we found our champions!

**Comment by jcchavezs** [comment]
<3

man. 8. apr. 2019, 02:53 skrev Adrian Cole <notifications@github.com>:
